### ISSUE TITLE
Assisting Mr. Ali in installing the project

### ISSUE THREAD

**Issue by OmsProjectTeam** [OmsProjectTeam/OSMProjact#11]
Please contact Mr. Ali, log in via AnyDesk, link the project to GitHub, and explain to him all the steps.

**Comment by masum-rayhan** [comment]
I take initiative to solve the issues. it'll be solve shortly

**Comment by masum-rayhan** [comment]
I have solved the problem
![image](https://github.com/OmsProjectTeam/OSMProjact/assets/73586966/21d44d23-917e-402e-920b-5b773577653f)
